apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: profilr
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: adeyomola/app:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-url
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-name
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: profilr
  labels:
    app: app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ${ssl_certificate}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443, 80"
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 443
      targetPort: 80
      name: app-port
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: app-port-2
