#spec:
#  env:
#  - name: DB_USER
#    valueFrom:
#      secretKeyRef:
#        name: db-secret
#        key: db-user
#  - name: DB_PASSWORD
#    valueFrom:
#      secretKeyRef:
#        name: db-secret
#        key: db-password

mongodb:
  uri: "mongodb://carts-db:27017/"
serviceMonitor:
  interval: 90s
  scrapeTimeout: 30s
  enabled: true
  additionalLabels:
    release: prometheus

#  template:
#    spec:
#      containers:
